kind: ServiceAccount
apiVersion: v1
metadata:
  namespace: default
  name: <account_name>
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: binding-df-admin
roleRef:
  kind: ClusterRole
  name: system:aggregate-to-admin
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: <account_name>
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: binding-df-edit
roleRef:
  kind: ClusterRole
  name: system:aggregate-to-edit
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: <account_name>
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: binding-df-view
roleRef:
  kind: ClusterRole
  name: system:aggregate-to-view
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: <account_name>
