apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy-try
  namespace: default
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
      usefor: try
  template:
    metadata:
      labels:
        app: nginx
        usefor: try
    spec:
      containers:
      - image: nginx:latest
        imagePullPolicy: Always
        name: nginx
        ports:
        - containerPort: 80
          protocol: TCP
      restartPolicy: Always